### ISSUE TITLE
[Bug] Page fill is adding extra line breaks

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-cli#118]
To repro (all steps are required)
* `npx playwright-cli@next codegen github.com`
* Type something in the search field on github.com
* Navigate to outlook.live.com from the browser window
* Click on sign in button (top right)
* Type something in the user name field
* Observe that codegen adds a new line break for every key press

**Comment by pavelfeldman** [comment]
I think the issue is that we don't account for the TTY width.
