### ISSUE TITLE
Add flag and environment variable to specify executablePath(s) for lightweight Alpine Linux container

### ISSUE THREAD

**Issue by braderhart** [microsoft/playwright-cli#120]
As you can see here, Puppeteer has an environment variable for `PUPPETEER_EXECUTABLE_PATH` as well as lowercased variant in `npm config`:

https://pptr.dev/#?product=Puppeteer&show=api-environment-variables

If I wanted to use Playwright in a lightweight Alpine Linux Docker container, then I'd need (and want) to use the distro browsers instead of the ones downloaded from Playwright.

See here for an example:

https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-on-alpine

Since Playwright has a CLI, unlike Puppeteer, it would be ideal to be able to specify an `executablePath` (and preferably an environment variable as well) for each browser.

The two primary browsers are Chromium and Firefox, however it looks like Playwright also supports WebKit. I'm not sure if there is a suitable package already for that on Alpine. All I could find are these:
- https://pkgs.alpinelinux.org/package/edge/community/x86_64/webkit2gtk
- https://pkgs.alpinelinux.org/package/edge/community/x86_64/qt5-qtwebkit

I'd like to request to add the following variables:
- `CHROMIUM_EXECUTABLE_PATH`
- `FIREFOX_EXECUTABLE_PATH`

And possibly a third, if there is indeed a working WebKit package for Alpine. If not, then I'll consider making one if someone can reach out to let me know more details about how it is built (or feel free to do it :pleading_face:):
- `WEBKIT_EXECUTABLE_PATH`

The last request is to get help figuring out the best way to modify the `playwright` dependency to `playwright-core`. I'm not a JavaScript developer by trade so I'm not sure the best way to do that using `npm` or `yarn`, or if I'd need to pull it from source and then modify it using `sed`. You can see the source of my Docker image here:

https://gitlab.com/equalos/skaffold/blob/master/playwright-cli/docker/playwright-cli/Dockerfile

**Comment by pavelfeldman** [comment]
Could you share more about your end goal?

**Comment by braderhart** [comment]
@pavelfeldman My biggest goal initially in this particular instance is to be able to use `playwright-cli` in a lightweight Alpine Linux container, for example to take screenshots or save PDFs. Once I have that working, then I'll begin testing the best method to enable codegen locally:

https://www.cbtechinc.com/desktop-docker-3-gpu-enabled-linux-graphical-containers/

And remotely:

https://github.com/swaywm/wlroots/pull/1988

The major benefit of doing this is:
- Alpine Linux is significantly smaller. Compressed, the image on Docker Hub is approx 197 MB vs the current Docker "official" image for Playwright which is about 4x larger.
  - Alpine Linux is the defacto lightweight Docker image solution for tiny images
- Alpine Linux has a large amount of up-to-date packages while the base image is very small (2.67 MB). This will make adding additional functionality for remote access using newer solutions like Wayland much easier to implement than other distros that are also much larger

Ultimately though, I would like to be able to also use Playwright for scraping and unit testing as well, so the goal would be to get these variables (and flags) added to Playwright (not just the CLI). Alpine is currently mentioned as not supported here:

https://github.com/microsoft/playwright/blob/master/docs/docker/README.md#alpine

This would resolve that, and at least make it comparable to what is being offered by Puppeteer which I think shows it has value and would help improve adoption.

**Comment by ryneeverett** [comment]
Seems like this feature would also satisfy #76.

**Comment by benhysell** [comment]
To tag along on this issue, I'd love the same for Windows, however I'm only looking to set the `executablePath` via the cli.  

If I'm to understand this thread, https://github.com/microsoft/playwright-sharp/issues/969#issuecomment-733797875, Windows can already do it via an environment variable.  

Happy to open another issue here if it makes sense to just track the Windows implementation.

**Comment by dgozman** [comment]
We are thinking about using codegen with custom setup (see https://github.com/microsoft/playwright/issues/5180). In this case, you would be able to provide `executablePath` to your own [`browserType.launch`](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions) call.

Merging into https://github.com/microsoft/playwright/issues/5180.
