### ISSUE TITLE
Download button from webpage clicked but download was not executed or download event didn't happen

### ISSUE THREAD

**Issue by supernooba** [microsoft/playwright-cli#124]
I was using the " python -m playwright codegen" it went well and I was able to navigate and click on the page while the code was autogenerated in the CLI. One of the steps is to click on a button that downloads an excel file. Upon clicking the button the code was generated but I did not observe any file downloaded, decided to complete the task by closing the webpage.

I've copied the autogenerated code into a python file then run the script. It executed well (headful) but then again at the end no download was executed.

**Comment by pavelfeldman** [comment]
@mxschmitt in case you want to fix it...

**Comment by supernooba** [comment]
> Playwright downloads files into a temporary location using unique names. You need to save them with a friendly name to keep them:
> 
> ```python
> const [download] = await Promise.all([
>   page.waitForEvent('download'),
>   page.click('text="Source code"')
> ]);
> download.saveAs("sources.zip")
> ```
> 
> You also need `acceptDownloads=True` in `browser.newContext`.
> 
> I'll update codegen to include that.

I appreciate your response and help. This worked like a charm! 

This is the code that worked for me:

# Click Download button
with page.expect_download() as download_info:
    page.click('input[name="ctl00$ContentPlaceHolder1$btnExportExcel"]')
download = download_info.value
download.saveAs("tpp_excel.xlsx")
