### ISSUE TITLE
'npx playwright-cli open example.com' failed

### ISSUE THREAD

**Issue by LSSCP** [microsoft/playwright-cli#137]
I follow the examples to start.
The first one seems to work fine.(npx playwright-cli codegen wikipedia.org).
But the second start to fail.
Is there any compatibility issue with the new version of nodejs or osx 11?

version
osx: 11.0
npm: 7.0.10
playwright-cli: 0.161.0
node.js: 15.2.0

###############

trace:
test@tests ~ % npx playwright-cli open example.com
/Users/test/node_modules/playwright-cli/lib/cli.js:267
            throw new Error(`Invalid target: '${language}'`);
                  ^

Error: Invalid target: 'undefined'
    at open (/Users/test/node_modules/playwright-cli/lib/cli.js:267:19)
npm ERR! code 1
npm ERR! path /Users/test
npm ERR! command failed
npm ERR! command sh -c playwright-cli open example.com

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2020-11-15T11_20_00_338Z-debug.log

################

the log file:

0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.2.0/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'playwright-cli',
0 verbose cli   'open',
0 verbose cli   'example.com'
0 verbose cli ]
1 info using npm@7.0.10
2 info using node@v15.2.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:project Completed in 0ms
9 timing config:load:file:/Users/test/.npmrc Completed in 0ms
10 timing config:load:user Completed in 0ms
11 timing config:load:file:/usr/local/Cellar/node/15.2.0/etc/npmrc Completed in 0ms
12 timing config:load:global Completed in 0ms
13 timing config:load:cafile Completed in 1ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:setUserAgent Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 7ms
18 verbose npm-session 98f02c5ae5bc31b5
19 timing npm:load Completed in 14ms
20 timing command:exec Completed in 978ms
21 verbose stack Error: command failed
21 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
21 verbose stack     at ChildProcess.emit (node:events:329:20)
21 verbose stack     at maybeClose (node:internal/child_process:1055:16)
21 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)

**Comment by kblok** [comment]
Fix on the way @LSSCP

**Comment by pavelfeldman** [comment]
This is fixed and published.
