### ISSUE TITLE
[Request] Allow installation of playwright-cli with single browser packages (playwright-chromium, ...)

### ISSUE THREAD

**Issue by bbo2adwuff** [microsoft/playwright-cli#155]
It would be great of we could install playwright-cli with the single browser packages:
- playwright-chromium
- playwright-webkit
- playwright-firefox

Currently it only works with playwright.

**Comment by pavelfeldman** [comment]
Why do you only need one, are you under strict resource constraints?

**Comment by bbo2adwuff** [comment]
No, actually not under strict resource constraints.
Just leaner, similar to single browser packages playwright.

But you're right, not really necessary...
But same argument holds for single browser packages of playwright as well!?
