### ISSUE TITLE
How to set ignoreHTTPSErrors on the underlying browser context?

### ISSUE THREAD

**Issue by nrhoffmann** [microsoft/playwright-cli#192]
I want to be able to point the codegen to a locally running version of my app. It has a self-signed certificate, so in the tests I set `ignoreHTTPSErrors: true` on the underlying context. Can we either add a `-k` flag to the CLI or have some way to pass arbitrary options down to the context?

**Comment by mxschmitt** [comment]
+1 sounds like a valid feature request to add ignoreHTTPSErrors as a CLI parameter which gets passed down to the context options.

**Comment by dgozman** [comment]
We are thinking about using codegen with custom setup (see https://github.com/microsoft/playwright/issues/5180). In this case, you would be able to provide `ignoreHTTPSErrors` to your own [`browser.newContext`](https://playwright.dev/docs/api/class-browser#browsernewcontextoptions) call.

Merging into https://github.com/microsoft/playwright/issues/5180.
