### ISSUE TITLE
Feature Request: Record network requests and save them as ready-to-use mocks

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright-cli#196]
I'm using playwright for integration tests. And I can't have a full environment for testing. So I mock api requests and test against them.

When I saw https://github.com/microsoft/playwright-cli/pull/194 this flow for authentication (which is super helpful, thank you), I thought it would be a great idea to generate code for network requests in a file and use them in specific tests (test by test basis in `it("...")` or `beforeEach` depending on the scenario.

In this case, I see it like so:
- Adding an option to the cli to save network requests to a given file (file name) like this `npx playwright-cli --save-network-requests=flow_1_requests.json codegen`
- Adding an API method in `playwright` to use a `mock file` or multiple files. This would allow to overwrite previous mocks if they are defined in two files. `playwright.useMockFiles(context, ['path/to/flow_1_requests.json', 'path/to/flow_2_requests.json'])`. It takes the `context` and paths to mock files.

**Comment by mxschmitt** [comment]
cool idea, might make sense to raise this request in the upstream repository: https://github.com/microsoft/playwright since this would be relevant for the core-playwright project too.

**Comment by haikyuu** [comment]
Done, thanks @mxschmitt

**Comment by dgozman** [comment]
Closing in favor of https://github.com/microsoft/playwright/issues/4928.
