### ISSUE TITLE
Add support for Playwright for Python

### ISSUE THREAD

**Issue by timonweb** [microsoft/playwright-cli#63]
First of all, thank you for what you've done already! Now to the question: can the tool generate code in Python so that it can be used with Playwright Python (https://github.com/microsoft/playwright-python)?

And if it's not, is it planned to be added?

**Comment by mxschmitt** [comment]
Hi, it's on our roadmap to add support for Python 👍🏻

**Comment by timonweb** [comment]
Great, I'm pumped! Have a nice weekend!

**Comment by mxschmitt** [comment]
Let's keep it open until we have implemented it. Btw. Are you using the sync or async version of Playwright for Python?

**Comment by timonweb** [comment]
@mxschmitt, sounds good! It's sync, I use it with pytest.

**Comment by mxschmitt** [comment]
Closed, there is support for Playwright for Python now.

**Comment by timonweb** [comment]
@mxschmitt sounds amazing, where can we get more info about it? I couldn't find anything.

**Comment by mxschmitt** [comment]
`npx playwright-cli codegen wikipedia.org --target python` should work. I will reopen it so we can add the corresponding documentation in the README.

**Comment by timonweb** [comment]
oh great, thank you so much! 👍
