### ISSUE TITLE
libenchant.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DanielTate** [microsoft/playwright-cli#68]
Ubuntu 20.04

Tried running  
`npx playwright-cli --device="iPhone 11" open wikipedia.org`

As per Readme.

Result:  
`[err] /home/dan/.cache/ms-playwright/webkit-1343/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libenchant.so.1: cannot open shared object file: No such file or directory`

**Comment by aslushnikov** [comment]
Hey @DanielTate, 

I can't repro this. Also, the shape of the error looks like an old version of `playwright-cli` is used against new browsers.

Could it be that you've being trying `playwright-cli` before and the old cached version is used? Just to be sure, could you please remove `$HOME/.npm` and try running the command again?

**Comment by DanielTate** [comment]
@aslushnikov I just installed `playwright` and `playwritght-cli` shortly before posting about the error. I may try your solution but I can't guarantee anything.

**Comment by mxschmitt** [comment]
Also tried to reproduce this. Was unfortunately not able to.

**Comment by mxschmitt** [comment]
Closed since we can't reproduce it. Let us know if you still experience that or have a reproducible for us e.g. with Docker.
