### ISSUE TITLE
codegen: fill does not capture full text string

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-cli#69]
Specific to bing.com

Repro steps:
* go to bing.com
* click on the search input field
* type "git" quickly
* type "hub" after a short pause
* the codegen shows only git (`await page.fill('input[aria-label="Enter your search term"]', 'git');`
  * it seems bing.com tries to autocomplete the field, which does not play well with codegen

**Comment by vivekbwaj** [comment]
I am also facing some issues with entering text in search field. I tried on this https://www.catch.com.au/

**Comment by mxschmitt** [comment]
> I am also facing some issues with entering text in search field. I tried on this https://www.catch.com.au/

The issue that catch.com.au is not working was tricky. They basically overwrite `String.replaceAll` in their code base which we use internally in a way that its broken and raises a error for our use case:

```js
    String.prototype.replaceAll = function(e, t, n) {
        return this.replace(new RegExp(e.replace(/([\/\,\!\\\^\$\{\}\[\]\(\)\.\*\+\?\|\<\>\-\&])/g, "\\$&"),n ? "gi" : "g"), "string" == typeof t ? t.replace(/\$/g, "$$$$") : t)
    }
```
(from their frontend bundle) So we can't do much in that case if they overwrite default methods.

**Comment by mxschmitt** [comment]
I tried to reproduce it a few weeks ago and wasn't. Let's reopen if its still reproducible.
