### ISSUE TITLE
Can this be used to generate video + audio from a page?

### ISSUE THREAD

**Issue by rememberlenny** [microsoft/playwright-cli#73]
I have been using a headful puppetteer for making screen recordings with audio, to turn HTML pages into video.

Is there a path for this to do something similar?

**Comment by mxschmitt** [comment]
We are curious in how you recorded the audio in puppeteer, was it by specifying custom arguments? If yes, it should work out of the box with Chromium.

**Comment by rememberlenny** [comment]
Here is the exact implementation: https://github.com/muralikg/puppetcam/blob/master/background.js#L26-L29

The puppeteer invokes chrome.desktopCapture, which saves audio. It works well for my purpose, which is to lay out a canvas via browser, press play, and record it to mp4.

I do this on a headful xvfb docker instance on a server.

**Comment by mxschmitt** [comment]
In general a modified variant of https://github.com/muralikg/puppetcam/blob/master/export.js for Playwright should also work with Playwright Chromium.

Adding such an integration natively to Playwright would make sense, if there are more users who request such a feature. (I can transfer it to the main repo, if we Chromium only support isn't enough for you)
