### ISSUE TITLE
How to properly output the generated code to a file?

### ISSUE THREAD

**Issue by colemars** [microsoft/playwright-cli#74]
My current output looks something like..

```
[38;5;205mconst[0m { chromium } = [38;5;220mrequire[0m([38;5;130m'playwright'[0m);

([38;5;205masync[0m () => {
  [38;5;205mconst[0m browser = [38;5;205mawait[0m chromium.launch({
    headless: [38;5;159mfalse[0m
  });
  [38;5;205mconst[0m context = [38;5;205mawait[0m browser.newContext();
})();
[1A[2K
  [38;5;23m// Open new page[0m
  [38;5;205mconst[0m page = [38;5;205mawait[0m context.newPage();
})();
```

**Comment by colemars** [comment]
Ah I see this isn't supported here https://github.com/microsoft/playwright-cli/issues/61#issuecomment-691314343

**Comment by mxschmitt** [comment]
> My current output looks something like..
> 
> ```
> [38;5;205mconst[0m { chromium } = [38;5;220mrequire[0m([38;5;130m'playwright'[0m);
> 
> ([38;5;205masync[0m () => {
>   [38;5;205mconst[0m browser = [38;5;205mawait[0m chromium.launch({
>     headless: [38;5;159mfalse[0m
>   });
>   [38;5;205mconst[0m context = [38;5;205mawait[0m browser.newContext();
> })();
> [1A[2K
>   [38;5;23m// Open new page[0m
>   [38;5;205mconst[0m page = [38;5;205mawait[0m context.newPage();
> })();
> ```

Hi! There is a "-o" CLI argument where you can save the output to a file.

**Comment by sjurgis** [comment]
@mxschmitt I'm not sure it works
```
$ npx playwright-cli codegen -o foo google.com
error: unknown option '-o'
$ npx playwright-cli codegen google.com -o foo
error: unknown option '-o'
$ npx playwright-cli -o foo codegen google.com
error: unknown option '-o'
# below works but no file created
$ npx -o foof.js playwright-cli codegen google.com
```
Also missing from help
```
npx playwright-cli help codegen
Usage: playwright-cli codegen [options] [url]

open page and generate code for user actions

Options:
  -h, --help  display help for command

Examples:

  $ record
  $ -b webkit record https://example.com
```

I'm using

```
    "playwright-chromium": "^1.4.0",
    "playwright-cli": "^0.5.2",
```

**Comment by eh-dub** [comment]
@sjurgis, there hasn't been a new release since #59 was merged. 
Anyone running the equivalent of `yarn add playwright-cli` won't get that feature.
Can a release be cut ASAP?

**Comment by sjurgis** [comment]
@eh-dub owww I've got confused by `25 commits to master since this release` which just showed diff between release and current master, rather than what was released. Stupid Github!

**Comment by eh-dub** [comment]
All good! It takes a village and all that 😉
