### ISSUE TITLE
Use codegen with existing browser and without incognito mode. 

### ISSUE THREAD

**Issue by IKoshelev** [microsoft/playwright-cli#76]
I'm in an enterprise environment, where I can't download arbitrary binaries. I have Chrome and Edgium installed on my machine, and I've been using them with puppeteer-core, providing path to executables. When I tried installing playwright-cli, I got a dns error for playwright.azureedge.net. I suspect this is due to my network restrictions. One way or another, my company firewalls won't let me download a custom browser. 

I managed to install playwright-cli via `npm install --ignore-scripts`, but it looks like I can't provide a path to my existing browser executable. I got around this by copying whole chrome folder to the path playwright-cli expected to find it, launched `npx playwright-cli codegen wikipedia.org` and it worked, window showed up and actions were recorded in script. But resulting window is in incognito mode, so I can't access any of my intranet sites (all requiring certificate to authenticate). 

I think this kind of restrictions will be typical for an enterprise environment, so would it be possible to use codegen with existing browser and without incognito mode?

**Comment by pavelfeldman** [comment]
You typically need a matching Playwright browser for it to operate. Are there any proxies you can use to download binaries? Playwright supports downloading browsers via corporate proxy.

**Comment by IKoshelev** [comment]
In an organization of 50k people, its near impossible to find someone with both will and authority to open up an avenue for binary download.

**Comment by dgozman** [comment]
We are thinking about using codegen with custom setup (see https://github.com/microsoft/playwright/issues/5180). In this case, you would be able to provide `executablePath` to your own [`browserType.launch`](https://playwright.dev/docs/api/class-browsertype#browsertypelaunchoptions) call.

Merging into https://github.com/microsoft/playwright/issues/5180.
