### ISSUE TITLE
[Feature] Publish pre-release as playwright-cli@next

### ISSUE THREAD

**Issue by eh-dub** [microsoft/playwright-cli#77]
With #74, I could start introducing playwright into my workplace. When can we expect the next release to be cut and how can we help?

**Comment by mxschmitt** [comment]
Which OS are you using? If you are using e.g. Visual Studio Code terminal or a modern terminal it should print it correctly.

**Comment by eh-dub** [comment]
Copy pasting from the terminal is a lossy operation.

I work with a website that has long URL slugs. These slugs cause the outputted code to wrap in the terminal. Copy pasting the terminal formatted code yields a broken script.

The `-o` flag circumvents this issue.

**Comment by arjun27** [comment]
Thanks for reaching out @eh-dub! We follow a monthly release cadence for the playwright and playwright-cli projects (with a new release around 6th of every month). While we support using tip-of-tree playwright with the `@next` tag, we don't have a similar setup configured for playwright-cli. I'll repurpose this as a feature request to add support for the next tag, so you can use tip-of-tree playwright-cli.

**Comment by mxschmitt** [comment]
We have now builds available for the latest tip-of-tree features which are usable by: "npm install plawright-cli@next"
