### ISSUE TITLE
PDF local HTML files issue

### ISSUE THREAD

**Issue by achwilko** [microsoft/playwright-cli#81]
First of all, great work with playwright-cli! 🚀 

I've tried using playwright-cli for the local HTML file but got an issue, eg.
```
npx playwright-cli pdf ./my-dir/index.html my-file.pdf
```
Any chance to fix the above one? Thank you in advance! 🍻

**Comment by mxschmitt** [comment]
Hi, for local files you need to prefix it with `file://` and use the full absolute path. Example for Linux:

```
npx playwright-cli pdf file:///$(pwd)/my-dir/index.html test.pdf
```

**Comment by achwilko** [comment]
Hi @mxschmitt, that helps a lot. I've tried again on windows and it seems that below is working correctly:
```
npx playwright-cli pdf file://C:\my-dir\index.html test.pdf
```
File input looks weird, especially on win, so if there is a chance for automatic local file detection then would be great. Once again, thanks for your help! 🍻
