### ISSUE TITLE
[codegen/python]: browser.close() merged with comment

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-cli#95]
Run `npx playwright-cli@next codegen --target python`, do some actions and close the browser.

```py
    # Close page
    await page.close()
    # Close browser    await browser.close()
asyncio.get_event_loop().run_until_complete(main())
```

We could add line breaks before `browser.close` and also before the last line for readability.

**Comment by pavelfeldman** [comment]
Fixed
