### ISSUE TITLE
[codegen/python]: Syntax highlighting of comments

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright-cli#97]
I believe the syntax highlighting being applied to Python code is JS-like. This isn't a huge deal for generated code, but would be nice if the comments were faded.

![Screen Shot 2020-10-08 at 11 57 05 AM](https://user-images.githubusercontent.com/284612/95501585-6372ab80-095d-11eb-814d-5810584b167e.png)

**Comment by pavelfeldman** [comment]
Fixed
